### ISSUE TITLE
  File "./oscar/datasets/oscar_tsv.py", line 114, in __init__     img_feat_offset_map = self.img_feat_offset_map[dataset_name][chunk_id] KeyError: '0'

### ISSUE THREAD

**Issue by wangxiao5791509** [microsoft/Oscar#115]
- INFO - root - loading lineidx: /userhome/Oscar/vinvl/pretrain_corpus/X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/gqa/QA_fileB.lineidx
07/20/2021 10:21:44 - INFO - root - loading lineidx: /userhome/Oscar/vinvl/pretrain_corpus/X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/gqa/predictions_gt.lineidx
 39%|███████████████████████████████████████████████████████████████                                                                                                 | 3691028/9357057 [17:52<15:56, 5924.66it/s]Traceback (most recent call last):
  File "oscar/run_oscarplus_pretrain.py", line 549, in <module>
    main()
  File "oscar/run_oscarplus_pretrain.py", line 324, in main
    args, is_distributed=args.distributed, arguments=arguments
  File "./oscar/datasets/build.py", line 132, in make_data_loader
    datasets = build_dataset(args)
  File "./oscar/datasets/build.py", line 38, in build_dataset
    datasets = [OscarTSVDataset(**cfg)]
  File "./oscar/datasets/oscar_tsv.py", line 114, in __init__
    img_feat_offset_map = self.img_feat_offset_map[dataset_name][chunk_id]
KeyError: '0'

**Comment by ckmstydy** [comment]
Hello. In line 382 of oscar_tsv.py, img_label_file_path is 
os.path.join(self.image_label_path[dataset_name], 'predictions_gt.tsv'),
However, the file I downloaded only contains prediction.tsv.  May I ask where to download predictions_gt.tsv in the code, or are these two the same?
