### ISSUE TITLE
add_od_labels False doesn't work

### ISSUE THREAD

**Issue by DesaleF** [microsoft/Oscar#169]
I have been playing with VinVL models for a while. I was trying to evaluate the model without the labels of the object detector. However after training the model with `add_od_label` set to `False`, is causing the following problem. I tried to bebug it but I did not manage to find the main cause of the problem. the error is cause by the shape mismat of input_ids at line `807` of `modeling_bert.py` file. I would approciate for any help regarding training and evaluating VinVL model without the object detection labels.

```python

Traceback (most recent call last):
  File "oscar/run_captioning.py", line 967, in <module>
    main()
  File "oscar/run_captioning.py", line 961, in main
    evaluate_file = evaluate(args, test_dataloader, model, tokenizer, checkpoint)
  File "oscar/run_captioning.py", line 678, in evaluate
    test(args, val_dataloader, model, tokenizer, predict_file)
  File "oscar/run_captioning.py", line 770, in test
    tsv_writer(gen_rows(), cache_file)
  File "/usr/src/app/Oscar/oscar/utils/tsv_file_ops.py", line 17, in tsv_writer
    for value in values:
  File "oscar/run_captioning.py", line 754, in gen_rows
    outputs = model(**inputs)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/src/app/Oscar/oscar/modeling/modeling_bert.py", line 631, in forward
    return self.generate(*args, **kwargs)
  File "/usr/src/app/Oscar/oscar/modeling/modeling_bert.py", line 806, in generate
    assert input_ids.shape == (batch_size, self.max_seq_len)
AssertionError
```

**Comment by linlin9527** [comment]
Can you tell me how you solved this problem? thank you
