### ISSUE TITLE
Getting "IndexError: list index out of range" error when accessing training features using the latest version of Oscar code

### ISSUE THREAD

**Issue by gsrivas4** [microsoft/Oscar#91]
I am running the latest version of Oscar code as per the instructions here - https://github.com/microsoft/Oscar/blob/master/VinVL_MODEL_ZOO.md#image-captioning-on-coco, and I getting below error: 
```
Traceback (most recent call last):
  File "oscar/run_captioning.py", line 1012, in <module>
    main()
  File "oscar/run_captioning.py", line 987, in main
    last_checkpoint = train(args, train_dataloader, val_dataloader, model, tokenizer)
  File "oscar/run_captioning.py", line 467, in train
    for step, (img_keys, batch) in enumerate(train_dataloader):
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/usr/local/lib64/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "oscar/run_captioning.py", line 140, in __getitem__
    features = self.get_image_features(img_idx)
  File "oscar/run_captioning.py", line 111, in get_image_features
    feat_info = json.loads(self.feat_tsv.seek(img_idx)[1])
IndexError: list index out of range
```
I have downloaded coco_captions dataset folder from here - https://github.com/microsoft/Oscar/blob/master/VinVL_DOWNLOAD.md#pre-trained-models. This download was missing the file `train.feature.tsv`. Hence, I downloaded this file from another [link](https://github.com/microsoft/Oscar/blob/master/DOWNLOAD.md#pre-trained-models) and added it to the dataset folder. 
I don't get the error when I use an older version of transformers - https://github.com/microsoft/Oscar/tree/9b07b6735267c0eb30fc2efd482d4295d13c7b4f. 
I did some debug and realized that the training features loaded by the older Oscar code have two field for each image - id and the feature embedding. However, the training features loaded by the latest Oscar code has only one field for each image which is the feature embedding. I have looked into the difference between the two commits of Oscar and couldn't find what could be causing this issue.

If someone could resolve the issue or have an idea what is causing the error, it would be really helpful if they can give some details about how to the fix the error.

**Comment by gsrivas4** [comment]
There was an issue at my end. Seems the data copying didn't happen correctly.
